version: '3.1'

services:

  nginx-hack-wooclap:
    container_name: nginx-hack-wooclap
    image: nginx-hack-wooclap:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - server-hack-wooclap
    networks:
      - network-hack-wooclap
    
  server-hack-wooclap:
    container_name: server-hack-wooclap
    image: server-hack-wooclap:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./server/app:/var/www/server
    networks:
      network-hack-wooclap:
        aliases:
          - server-hack-wooclap
    command: python server/app.py

networks:
  network-hack-wooclap