version: '3'
services:
  # Service du client React
  client:
    container_name: react-client
    build:
      context: ./client  # Spécifiez le répertoire où se trouve le code du client React
      dockerfile: Dockerfile  # Assurez-vous que vous avez un Dockerfile dans le répertoire du client
    ports:
      - "3000:3000"  # Port du client React

  # Service du serveur API Python
  server:
    container_name: python-api-server
    build:
      context: ./server  # Spécifiez le répertoire où se trouve le code du serveur Python
      dockerfile: Dockerfile  # Assurez-vous que vous avez un Dockerfile dans le répertoire du serveur
    ports:
      - "5002:5002"  # Port du serveur API Python
    depends_on:
      - client  # Assurez-vous que le client React soit démarré avant le serveur Python
