version: "3.1"

services:
  nginx_hack_wooclap:
    image: nginx:1.15
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 81:80
      - 443:443
    networks:
      - my-network
    depends_on:
      - server
  server_hack_wooclap:
    build:
      context: .
      dockerfile: server/app/Dockerfile
    container_name: server
    command: python server/main.py
    restart: always
    volumes:
      - ./server/app:/var/www/server
    networks:
      my-network:
        aliases:
          - server
networks:
  my-network: